Update debug

diff --git a/debug b/debug
--- a/debug
+++ b/debug
@@ -1,18 +1,15 @@
 #/bin/bash
 echo "------------------------------------------------------"
 echo "        Syntax Copyright Liam Stanley 2012-2013       "
-echo "  This way of debugging Syntax is under development.  "
+echo "      Debugging Syntax is still under development.    "
 echo "         -----------------------------------          "
-echo "          Make sure PHP4 or 5 is installed!           "
+echo "      Make sure you have PHP4 or PHP 5 installed      "
 echo "------------------------------------------------------"
-echo "------------------------------------------"
-echo "Checking Syntax executables in $PWD now..."
-echo "------------------------------------------"
-find . -name \*.php -exec php -l "{}" \; || { echo 'Compiling method failed...' ; exit 1; }
-echo "------------------------------------------------------------"
-echo "Checking Syntax setup and bot config settings in $PWD now..."
-echo "------------------------------------------------------------"
-find . -name \*.inc -exec php -l "{}" \; || { echo 'Compiling method failed...' ; exit 1; }
+echo "-------------------------------------------------"
+echo "Syntax checking all files in $PWD starting now..."
+echo "-------------------------------------------------"
+find . -name \*.php -exec php -l "{}" \; || { echo 'Syntax Checking method failed...' ; exit 1; }
+find . -name \*.inc -exec php -l "{}" \; || { echo 'Syntax Checking method failed...' ; exit 1; }
 echo "-------------------------------------------"
 echo "If no errors resided, then were good to go!"
 echo "-------------------------------------------"
